version: 2
jobs:
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
            - ./node_modules
          key: dependency-cache-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: levity/dapptools-node-latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: |
            source /home/circleci/setup-env.sh
            yarn test:ci
            USE_FS_CACHE=1 yarn build
            yarn add --dev codecov
            ./node_modules/.bin/codecov
      - save_cache:
          paths:
            - node_modules
            - ./node_modules
            - ./.next/cache
          key: dependency-cache-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  mainflow:
    jobs:
      - install
      - test:
          requires:
            - install
